(function(){
'use strict';
var months=['janeiro','fevereiro','março','abril','maio','junho','julho','agosto','setembro','outubro','novembro','dezembro'];
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function id(rows){var d=new Date(),stamp=''+d.getFullYear()+String(d.getMonth()+1).padStart(2,'0')+String(d.getDate()).padStart(2,'0'),prefix='DOC-'+stamp+'-',n=rows.filter(function(x){return x.id.indexOf(prefix)===0}).length+1;return prefix+String(n).padStart(4,'0')}
function normalize(form){var fd=new FormData(form),f={};fd.forEach(function(v,k){f[k]=String(v).trim()});var d=new Date(f.Ass_data+'T12:00:00');if(isNaN(d.getTime()))throw new Error('Informe uma data válida.');f.Ass_dia=String(d.getDate()).padStart(2,'0');f.Ass_mes=months[d.getMonth()];f.Ass_ano=String(d.getFullYear());return f}
function html(f,reg){return '<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>'+esc(reg)+' - '+esc(f.Colab_nome)+'</title><style>@page{size:A4;margin:30mm 20mm 20mm 30mm}body{font-family:Arial,sans-serif;font-size:12pt;line-height:1.5;color:#000;margin:0}h1{text-align:center;font-size:12pt;margin:0 0 12px}h2{font-size:12pt;margin:16px 0 6px}p{text-align:justify;text-indent:1.25cm;margin:0}.incred{color:red}table{width:100%;border-collapse:collapse;margin:8px 0 14px;font-size:10pt;line-height:1.25}th,td{border:1px solid #777;padding:7px;vertical-align:middle}th{background:#e9eef5;text-align:left}.meta,.noindent,.sign{text-indent:0}.meta{text-align:center;font-size:10pt;margin-bottom:15px}.sign{text-align:center;margin-top:30px}</style></head><body>'+ 
'<h1>TERMO DE RESPONSABILIDADE - ENTREGA DE EQUIPAMENTOS</h1><p class="meta incred">Nº '+esc(f.Num_incident)+'</p>'+ 
'<p>A CM Hospitalar S.A., pessoa jurídica de direito privado, entrega ao funcionário abaixo identificado o equipamento descrito neste termo para utilização relacionada às suas atividades profissionais.</p>'+ 
'<h2>DESCRIÇÃO DO EQUIPAMENTO</h2><table><tr><th>Marca</th><td>'+esc(f.Equip_marca)+'</td><th>Modelo</th><td>'+esc(f.Equip_modelo)+'</td></tr><tr><th>Número de Série</th><td>'+esc(f.Equip_serial)+'</td><th>Hostname</th><td>'+esc(f.Equip_hostname)+'</td></tr><tr><th>Patrimônio</th><td colspan="3">'+esc(f.Equip_patrimonio)+'</td></tr></table>'+ 
'<h2>DADOS DO FUNCIONÁRIO</h2><table><tr><th>Nome</th><td colspan="3">'+esc(f.Colab_nome)+'</td></tr><tr><th>Cargo</th><td>'+esc(f.Colab_cargo)+'</td><th>Área</th><td>'+esc(f.Colab_area)+'</td></tr><tr><th>Local/Unidade</th><td>'+esc(f.Colab_local)+'</td><th>Centro de custo</th><td>'+esc(f.Colab_custo)+'</td></tr><tr><th>Gestor</th><td>'+esc(f.Colab_gestor)+'</td><th>E-mail</th><td>'+esc(f.Colab_email)+'</td></tr></table>'+ 
'<h2>1 COMPROMISSO, CUIDADOS E MANUSEIO DOS EQUIPAMENTOS</h2><p>O funcionário compromete-se a utilizar e conservar adequadamente o equipamento recebido, mantendo-o sob sua guarda e não o cedendo a terceiros sem autorização da empresa. Deverá comunicar prontamente qualquer problema, dano, perda, furto, roubo ou extravio.</p>'+ 
'<h2>2 DEVOLUÇÃO DOS EQUIPAMENTOS</h2><p>O equipamento deverá ser devolvido quando solicitado pela empresa, inclusive em situações de substituição do equipamento, mudança da necessidade de uso ou encerramento do vínculo aplicável, observadas as políticas internas.</p>'+ 
'<h2>3 RECEBIMENTO DOS EQUIPAMENTOS E DISPOSIÇÕES FINAIS</h2><p>O funcionário declara ter recebido o equipamento descrito neste documento e estar ciente das responsabilidades relacionadas à sua utilização, conservação e devolução.</p>'+ 
'<p class="noindent" style="margin-top:22px">São Paulo, '+esc(f.Ass_dia)+' de '+esc(f.Ass_mes)+' de '+esc(f.Ass_ano)+'.</p><p class="sign">________________________________________<br>'+esc(f.Colab_nome)+'<br>Assinatura do Funcionário</p></body></html>'}
function openContract(f,reg,autoPrint){var w=window.open('','_blank');if(!w)throw new Error('O navegador bloqueou a nova janela. Permita pop-ups para este arquivo.');w.document.open();w.document.write(html(f,reg));w.document.close();if(autoPrint){setTimeout(function(){try{w.focus();w.print()}catch(e){}},500)}return w}
window.TermContract={makeId:id,normalize:normalize,open:openContract};
})();
